### PR TITLE
Add SceDriverUser module and with a lot of new NIDs ;-) CB#2

### PR DESCRIPTION
**Pull request by CelesteBlue-dev**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
@CelesteBlue-dev can you split this? it can't pass CI test.

**Comment by xyzz** [comment]
this is backwards incompatible

**Comment by devnoname120** [comment]
No update for a long time, closing.

**Comment by CelesteBlue-dev** [comment]
I haven't updated because xyz told it breaks compatibility. no offense.

**Pull request closed without merging**
