### PR TITLE
Added error code for SceAppMgr

### PR DESCRIPTION
**Pull request by bythos14**
Credit also to @MerLev

Thanks to @Princess-of-Sleeping for guiding the blind.

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
@bythos14 could you give reference link?

**Comment by bythos14** [comment]
No reference, @MERLev and I reversed that error code while trying to figure out why he couldn't load an app using SceAppMgr from the kernel.

**Comment by bythos14** [comment]
There are numerous checks within SceAppMgr to ensure that only SceShell can run certain loader functions, if one of those checks fail then `0x8080201F` is returned. Two of those checks is to use ksceSblACMgrIsShell, and to check the the current process ID to see if it matches SceShell's. That's my explanation of the error code.

**Comment by Princess-of-Sleeping** [comment]
`0x8080201F` is not SCE_APPMGR_ERROR_NOT_SHELL.

it SCE_APPMGR_ERROR_NOEXEC.

**Comment by bythos14** [comment]
Came up with the name myself, so not surprised that it's wrong. So does this error indicate no permissions to start a separate program? Am I wrong in my assumption of it's purpose?

**Comment by Princess-of-Sleeping** [comment]
In this case, it does not apply to SCE_APPMGR_ERROR_NOT_SHELL.

```
int SceAppMgrForDriver_29421DCD(int a1, ...){

	if(ksceKernelGetProcessId() != 0x10005)
		return 0x8080201F;

	/*
	 * doing some
	 */

	return res;
}
```

**Comment by bythos14** [comment]
So the error will be returned when an unauthorized process tries to access functionality not allowed to it. I'll make the necessary adjustments tomorrow.

**Comment by bythos14** [comment]
Adjustments made.

**Pull request merged**
