### PR TITLE
Added ksceKernelRemapBlock to headers

### PR DESCRIPTION
**Pull request by yifanlu**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
please rebase from master.

**Comment by yifanlu** [comment]
Can't you rebase and merge?

**Comment by d3m3vilurr** [comment]
i can do. but please make pr with last master if you haven't other reason.

travis ci system tested committed tree instead merged tree. sometimes this rule make false alarm like this pr.(download sdk problem already fixed)

basically failed commit cannot merge without more reviewer cost. (also we may not check build safety)

ps. if we use broken ci system like few days ago , i'll allow this pr. but now ci system backed on :)
so i requested rebase.

**Comment by yifanlu** [comment]
> download sdk problem already fixed

is it though? it seems like the error is that...

**Comment by devnoname120** [comment]
@yifanlu Your branch doesn't have the commit that fixes it. If you rebase Travis will run properly.

**Comment by d3m3vilurr** [comment]
this pr not fixed that problem so pr make error, (because fork before fix)

**Pull request merged**
