### PR TITLE
Add function signature for _sceAppMgrDestroyAppByName

### PR DESCRIPTION
**Pull request by himanshugoel2797**

### CODE REVIEW

**Comment by xyzz** [comment]
it would be helpful to add a comment specifying what `name` is

**Comment by himanshugoel2797** [comment]
ah, right ok, will do

**Comment by himanshugoel2797** [comment]
Well, figured it out

**Comment by devnoname120** [comment]
What is it supposed to do? Kill a running app or uninstall it?

**Comment by himanshugoel2797** [comment]
It kills an app to the point of peeling away the app's LiveArea screen.

**Pull request merged**
