### PR TITLE
Revert "Added sceGxmTextureInitSwizzledArbitrary function prototype"

### PR DESCRIPTION
**Pull request by d3m3vilurr**
Reverts vitasdk/vita-headers#469

I couldn't find any license permit from vita3k yet.

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
I'm communicating this with vita3k members.
temporary reverts it until resolve the problem.

**Comment by bythos14** [comment]
Oh, my apologies. I forgot to account for the difference in licenses.

**Comment by Zangetsu38** [comment]
why revert ? i no understund, is just good 🤔

**Comment by Zangetsu38** [comment]
I approve the use of this code as MIT

**Pull request merged**
