### PR TITLE
Add some sce_paf_private functions

### PR DESCRIPTION
**Pull request by devnoname120**

### CODE REVIEW

**Comment by devnoname120** [comment]
`sce_paf_private_strncpy: 0x5883A6E3` looks wrong, it's actually `sce_paf_private_memcpy`.

**Comment by TheOfficialFloW** [comment]
Can you test it?

**Comment by TheOfficialFloW** [comment]
Also why are there two memmove? Please note the difference in the header

**Comment by devnoname120** [comment]
The assembly of `0x5883A6E3` directly calls `sceClibMemcpy`, and it doesn't set the last byte to `\0`.

**Comment by devnoname120** [comment]
The two memmove have some slightly different assembly but they do the exact same thing

**Comment by TheOfficialFloW** [comment]
Oh ok, feel free to remove it then.

**Pull request merged**
