### PR TITLE
Add more SceBt and SceKernelThreadMgr NIDs

### PR DESCRIPTION
**Pull request by xerpi**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
can you rebase instead merge?

**Comment by xerpi** [comment]
Tbh I have no idea how to do that, I'm pretty noob at git, still don't know how I managed to get that merge commit working.

**Comment by d3m3vilurr** [comment]
`git rebase origin/master` then `git push origin SceBtForDriver_nids -f`
(this case origin is vitasdk repo)

**Comment by xerpi** [comment]
Should I do this right now or go back to the commit first?

**Comment by xerpi** [comment]
Merge branch SceBtForDriver_nids instead.

**Comment by d3m3vilurr** [comment]
haha..... it's github problem & my mistake
sorry `git push origin SceBtForDriver_nids -f`'s origin should be your remote repo tag.

**Pull request closed without merging**
