### PR TITLE
psp2: Add SCE_KERNEL_MEMBLOCK_TYPE_USER_RX

### PR DESCRIPTION
**Pull request by d3m3vilurr**
sceKernelAllocMemBlockForVM would alloc the memchunk typed by 0x0C20D050

### CODE REVIEW

**Comment by xerpi** [comment]
Feel free to merge it I guess.

**Comment by d3m3vilurr** [comment]
hehe, i just want to finish making the mmap/munmap patch. ;)
that's reason why i didn't merge it

**Comment by xerpi** [comment]
Oops sorry 😅

**Comment by d3m3vilurr** [comment]
it's okay. i didn't explain it  :p

**Pull request merged**
