### PR TITLE
Add sceRegMgr functions

### PR DESCRIPTION
**Pull request by joel16**
I'm not exactly sure where this would fit in the docs -> definitions.dox, so please let me know and I'll make the changes.

### CODE REVIEW

**Comment by devnoname120** [comment]
You need to define the group in `docs/definitions.dox` as well.

**Comment by joel16** [comment]
I'm aware of that, but what I was asking is I'm not sure what grouping you'd want me to put this under. Example, defgroup Miscellaneous or defgroup SystemStatus?

**Comment by devnoname120** [comment]
Maybe `SystemParams`?

**Comment by joel16** [comment]
Done, thanks for looking into it noname sensei.

**Pull request merged**
