### PR TITLE
Move libraries to correct modules.

### PR DESCRIPTION
**Pull request by bythos14**
SceAppMgrUser and SceMotion are within SceDriverUser

SceAudiodecUser, SceAudioencUser, SceCodecEngineUser, SceJpegUser, SceJpegEncUser and SceVideodecUser are all in SceAvcodecUser

SceDeci4p, SceFios2, SceLocation and SceLocationExtension modules are actually named SceDeci4pUserp, SceLibFios2, SceLibLocation and SceLibLocationExtension respectively.

SceDTrace is in SceDeci4pDtracep.

There are other libraries in db.yml which are under the wrong module.

### CODE REVIEW

**Comment by cuevavirus** [comment]
https://github.com/vitasdk/vita-headers/issues/439#issuecomment-583873328

prophetic

**Comment by bythos14** [comment]
You've been proven correct. Congrats.

**Comment by bythos14** [comment]
You should probably fix it in DolceSDK, the errors are still there.

**Comment by cuevavirus** [comment]
already did but not yet merged in master.

**Comment by bythos14** [comment]
Can this PR be left open please to prevent someone from making the same pull request in the future .

**Comment by d3m3vilurr** [comment]
@cuevavirus I also know swear. how about get the respect and manner to other developers.
your activity of relicense makes pissing off to other maintainers. do you happy?
do not steal & fuck up again

**Comment by cuevavirus** [comment]
Versioning is useless without maintainers. In case you haven't noticed, I've been maintaining the next version of vitasdk right here https://github.com/DolceSDK.

**Comment by bythos14** [comment]
This is starting to get unnecessarily aggressive... Y'all mind not doing this, please?

**Pull request closed without merging**
