### PR TITLE
Remove -l prefix from library linking hints

### PR DESCRIPTION
**Pull request by devnoname120**
This is long overdue.
#123

### CODE REVIEW

**Comment by CelesteBlue-dev** [comment]
@devnoname120 Why removing -l ? And in Makefile, have us to edit lib imports or not ?

**Comment by devnoname120** [comment]
The `-l` syntax was too specific.
We recommend using `CMakeLists.txt` files, plain `Makefile` should not be used.

Check the [samples](https://github.com/vitasdk/samples) to see how to use CMake.

**Comment by Rinnegatamante** [comment]
psp2/io/fcntl.h requires Sceiofilemgr_stub (https://github.com/vitasdk/vita-headers/blob/master/db.yml#L2143) but in current header file is reported as it doesn't require a linked library.

**Comment by devnoname120** [comment]
Please make a new pull request to address this issue.

**Pull request merged**
