### PR TITLE
Added Json Library

### PR DESCRIPTION
**Pull request by bythos14**
Will finish documenting later.

### CODE REVIEW

**Comment by bythos14** [comment]
I'll try to fix the travis-ci errors and do more testing before reopening this pull request

**Comment by Princess-of-Sleeping** [comment]
The vitasdk header is basically C language.
The one you added is C++.

**Comment by bythos14** [comment]
So should I give up on it getting merged? Or is there something I can do to adapt it to using C++?

**Comment by Princess-of-Sleeping** [comment]
maybe

https://github.com/vitasdk/vita-headers/blob/master/include/psp2kern/appmgr.h#L12-L14
https://github.com/vitasdk/vita-headers/blob/master/include/psp2kern/appmgr.h#L54-L56

**Comment by cuevavirus** [comment]
please wait until dolcesdk adds this header at which point you can copy paste it as usual

**Comment by bythos14** [comment]
Well that's insulting, but thanks for the error codes, I'll be sure to credit you when I reopen the pull request.

**Comment by joel16** [comment]
> please wait until dolcesdk adds this header at which point you can copy paste it as usual

You and your kiddie group always seem to go around saying shit like this as if you brought up the entire toolchain/sdk yourselves. For the record your "dolceSDK" would never exist without the vita toolchain nor vitasdk-headers/packages. Not to mention the fact your "group" GPL poisoned the vitasdk. Stop insulting others developers who contribute here when you clearly have nothing better to do in your time.

**Pull request closed without merging**
