### PR TITLE
[WIP] psp2kern: Rename ksceSysrootUse*Storage

### PR DESCRIPTION
**Pull request by d3m3vilurr**
rollback ksceSysrootUseExternalStorage to ksceSysrootIsManufacturingMode
rename ksceSysrootUseInternalStorage to ksceSysrootIsInternalStorageEnabled

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
we still have conversation these names in discord
wait to merge until get agreement.

**Comment by d3m3vilurr** [comment]
I don't agree `ksceSysrootIsInternalStorageEnabled` naming. I suggested `ksceSysrootGetEnabledStorageType` then define storage type enum.
@CelesteBlue-dev doesn't agree `ksceSysrootIsManufacturingMode`. he suggested `ksceSysrootIsExternalStorageEnabled`.

**Comment by Princess-of-Sleeping** [comment]
can name them because the same entry exists
```
// SceSysrootForKernel
//455: ksceSysrootUseInternalStorage 0x50fe3b4d @OFF: 0x2101d VADDR: 0x8102101d
//456: ksceSysrootUseExternalStorage 0x55392965 @OFF: 0x20fc9 VADDR: 0x81020fc9

//742: SceSysrootForDriver_50FE3B4D 0x50fe3b4d @OFF: 0x2101d VADDR: 0x8102101d
//746: SceSysrootForDriver_55392965 0x55392965 @OFF: 0x20fc9 VADDR: 0x81020fc9
```

**Comment by d3m3vilurr** [comment]
replaced #495

**Pull request closed without merging**
