### PR TITLE
db: Rename hash functions

### PR DESCRIPTION
**Pull request by d3m3vilurr**
all applied camelCase
it also fixed typo `ksceSblDmac5AEsCbcDec`

### CODE REVIEW

**Comment by CelesteBlue-dev** [comment]
nice but if you rename then better to use proper names. look wiki: WithKeygen -> NP

**Comment by d3m3vilurr** [comment]
well...WithKeygen would be okay, imo that was called with `sceSblDmac5EncDecKeyGen` data by user side
but actually i don't care both, just I need definition of `NP`

**Comment by CelesteBlue-dev** [comment]
NP = NoPortability. That's because these NP functions dont use enc_dec_with_portability_sm.self (a f00d module) that stores the keys.

**Comment by d3m3vilurr** [comment]
ok. it reasonable name. i'll change it.

**Comment by d3m3vilurr** [comment]
hm we already have `WithPortability` postfix

1. remove them
2. NP replace to `WithPortability` postfix.

what do you prefer?

**Comment by CelesteBlue-dev** [comment]
@devnoname120 and me made a tool to get names from the wiki and then insert into db.yml
I think it could be easier to use this tool.
In all cases, take the names from wiki then fix typos.

**Comment by d3m3vilurr** [comment]
as you knows we(vitasdk team) don't care original sce names.
we just focus that names have readability, right meaning and backward compatibility.
also this patchset is one of polishing definition after importing.

**Comment by d3m3vilurr** [comment]
okay no more conversation here.
only remain issues are
1. `WithPortability` part
2. `NoPortability`(`WithKeygen`) part.

I agree that `WithKeygen` is meanless name, but `NP` also too short/meanless postfix.
just it's better than `WithKeygen`.

my options are
1. remove `WithPortability` postifx
2. we use `WithoutProtability` instead `NP`

I just merge current code and I'll make an another issue for that.

**Pull request merged**
