### PR TITLE
[WIP] Add SceLibcParam to types.h.

### PR DESCRIPTION
**Pull request by bythos14**
In conjunction with https://github.com/vitasdk/vita-toolchain/pull/155, use of SceLibc should become viable.

### CODE REVIEW

**Comment by frangarcj** [comment]
@d3m3vilurr is this the best place? Or another header?

**Comment by d3m3vilurr** [comment]
i have no idea of the best place yet.
could you share the using example of it?

**Comment by d3m3vilurr** [comment]
ok. it would related `SceProcessParam` and `sceKernelGetProcessParam` of the `SceProcessmgr`. right? so how about adding the type into `psp2/kernel/processmgr.h`?

**Comment by bythos14** [comment]
I've been looking at this more closely now, and I'm starting to think it may not have been the most optimal choice unfortunately. Can this be put on hold until I get it all sorted out?

**Comment by d3m3vilurr** [comment]
sure. could you add `[WIP]` mark into issue title? then remove it after ready to merge & review it.

**Comment by bythos14** [comment]
Yeah, thanks.

**Pull request closed without merging**
