### PR TITLE
Add SceSystimer prototypes

### PR DESCRIPTION
**Pull request by bythos14**
The function names are guessed

### CODE REVIEW

**Comment by Princess-of-Sleeping** [comment]
maybe you forget header comment.

```C
/**
 * \kernelgroup{SceSystimer}
 * \usage{psp2kern/systimer.h,SceSystimerForDriver_stub}
 */
```

**Comment by bythos14** [comment]
Ah, I did forget it. Thanks

**Comment by Princess-of-Sleeping** [comment]
And since SceSystimer is the base kernel, can you move it to `psp2kern/kernel/systimer.h`?

**Comment by bythos14** [comment]
Done

**Comment by Princess-of-Sleeping** [comment]
Thank you.

**Pull request merged**
