### PR TITLE
Added Json Library. Redo

### PR DESCRIPTION
**Pull request by bythos14**
Added most of the exported SceLibJson functions. A couple were problematic so I omitted them. Thanks to cuevavirus for error codes.

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
it seems copied from official sdk. we can't allow it.
if you had reversed it, please share the information. (and at that cases, it would be c mapping)

**Comment by bythos14** [comment]
What information would be sufficient and suitable? I got the function and class names from db.yml and popped them in a demangler

**Comment by d3m3vilurr** [comment]
imo, you might copied error codes from official sdk (or cuevavirus did it). it's not allowed for preventing license violation.
you should remove copied parts of the pr.
(maybe we already have the copied parts in this project, but it doesn't mean, we allow to copy from leaked/official sdk)

**Comment by frangarcj** [comment]
https://pastebin.com/RmfPVDs3

**Comment by bythos14** [comment]
I did as you recommended for the error codes. Also made other minor changes.

**Comment by d3m3vilurr** [comment]
@bythos14 if you add new changes, you should make the new pr that this pr was closed & it doesn't update anymore until reopen.

**Comment by bythos14** [comment]
Okay, thank you

**Pull request closed without merging**
