### PR TITLE
Update SceNetPs

### PR DESCRIPTION
**Pull request by CelesteBlue-dev**

### CODE REVIEW

**Comment by yne** [comment]
This is a breaking change, since you removed `ksceNetSocketClose`  and `sceNetConnectForSyscalls`  (but are still documented in the net.h headers).

**Comment by Princess-of-Sleeping** [comment]
If it can not be compiled, developers can fix the source

**Comment by CelesteBlue-dev** [comment]
fixed

**Comment by CelesteBlue-dev** [comment]
fixed

**Comment by yne** [comment]
Thanks, one last thing, could you do it in this order :
```
int ksceNetSocketClose(int s);
...
#define ksceNetClose ksceNetSocketClose
```
this way, all NIDS you've just added are real prototypes,
and the `#define` are only for legacy purpose.

**Pull request merged**
