### PR TITLE
NpCommerce2 DRM Stuffs

### PR DESCRIPTION
**Pull request by KuromeSan**
Used to fetch download list.

### CODE REVIEW

**Comment by cuevavirus** [comment]
stolen from me without credit

image

**Comment by frangarcj** [comment]
Why is it stolen if him has reversed it? Isn’t it the same you do with sce binaries?

**Comment by cuevavirus** [comment]
because he did not state the source . he's welcome to reverse it from sce binaries

**Comment by frangarcj** [comment]
I won’t decide on this because I can be biased. @d3m3vilurr opinion?

**Comment by Princess-of-Sleeping** [comment]
This PR is like trying to extract some data (example: sce font data) from the SCE module, remake it into a sample, and add it to `vitasdk/samples`.

**Comment by d3m3vilurr** [comment]
@frangarcj me too. i'm also biased.
but I also asked it to @KuromeSan.
actually i think, it can be gray zone. if we can receive  a patch from reversing result sce resources, what is different receiving patch from homebrew?

**Comment by Princess-of-Sleeping** [comment]
If that homebrew using illegal sdk?

**Comment by cuevavirus** [comment]
because he did not state the source . he's welcome to reverse it.

**Comment by Princess-of-Sleeping** [comment]
Yeah. In PR, not only the result but also the process is important.

**Comment by d3m3vilurr** [comment]
in the screenshot, you didn't share the source code, so we can expect, he reversed it from somewhere
so why important source? if she reversed it from your homebrew, what is special than sce binaries?

**Comment by cuevavirus** [comment]
in previous cases when someone has reversed something and submitted to this repository, it came from sce binaries. in this unprecedented case, it was reversed from my program and not sce binaries. this was not made clear by the submitter.

**Comment by d3m3vilurr** [comment]
what you mean
`in this unprecedented case, it was reversed from my program and not sce binaries. this was not made clear by the submitter.`

so you mean, you don't need confirm from sce when you reversing of sce binaries, but people need confirm from you whan they try to reversing of your binaries?
is it right? and do you think it makes sense?

**Comment by cuevavirus** [comment]
you have misunderstood. in previous cases when someone has reversed something and submitted to this repository, it's assumed that it came from sce binaries. in this unprecedented case, that is not true and must be made apparent.

**Comment by d3m3vilurr** [comment]
You misunderstood too. I got what your point. but I mean this case is nothing different as reversing SCE binaries.
so your binaries is also not special.

when you reverse the SCE binaries or try to reverse vita games, it's still located gray area.
it's totally same case reverse your application.

this problem is `chicken or the egg` case, but logically it's same.

**Comment by cuevavirus** [comment]
if you think someone can read some strings from my binary and add it here without credit, then i can read some strings from vitasdk's binary and take it without credit

is it right? and do you think it makes sense?

**Comment by isage** [comment]
@d3m3vilurr it is, but sce never asked for credit, @cuevavirus did.

@cuevavirus will rewriting commit message as "Added NpCommerce2 DRM NIDs (reversed from cuevavirus homebrew)" suffice?

**Comment by cuevavirus** [comment]
that will be ok

**Comment by isage** [comment]
^ @KuromeSan please squash your commits and rewrite commit message.

**Comment by d3m3vilurr** [comment]
@isage don't finish the conversation of this

**Comment by d3m3vilurr** [comment]
@cuevavirus after this time, if you have any opinion of pr/project and others in this vitasdk orgs, send email / dm on discord to me. do not comment in here. we still have biased to you.

@KuromeSan please check the my dm and answer to me.

**Comment by d3m3vilurr** [comment]
it will replace by #722 & future works.

**Pull request closed without merging**
