### PR TITLE
Added sceKernelGetModel signature and NID

### PR DESCRIPTION
**Pull request by himanshugoel2797**

### CODE REVIEW

**Comment by DaveeFTW** [comment]
Can you write a small description for this? Would also be useful to provide an enum for the return values, assuming its similar to PSP.

**Comment by himanshugoel2797** [comment]
I can do the description, don't have all the values to be able to do the enum.
On the PCH-1000 it returns 0x10000, don't know about others.

**Comment by joel16** [comment]
Slim returns 0x10000 as well. Vita TV however returns 0x20000.

**Comment by endrift** [comment]
Functions that should not be passed arguments take `(void)`, not `()`. `()` means you can pass any arguments (only in C).

**Comment by himanshugoel2797** [comment]
I know, I thought that it'd be better to stick to just `()` to be consistent with the existing signatures.

**Comment by himanshugoel2797** [comment]
Just added the comments and enum

**Comment by xyzz** [comment]
Ok we can fix the () stuff later (and on the whole repo at once).

**Pull request merged**
