### PR TITLE
Added missing lib refs, fixed enum name in jpegenc.

### PR DESCRIPTION
**Pull request by Rinnegatamante**
Added missing lib refs, fixed enum name in jpegenc.

### CODE REVIEW

**Comment by devnoname120** [comment]
`SceLibKernel_stub.a` is included by default, no need to add thé link hint.

**Comment by Rinnegatamante** [comment]
So, should i remove such reference? It was already used for several headers (in the old SceKernel_stub form).

**Comment by devnoname120** [comment]
Yes, it would be nice if you could remove the other locations where is appears. :+1:

**Comment by Rinnegatamante** [comment]
Done

**Pull request merged**
