### PR TITLE
modulemgr.h: correct offsets in SceKernelModuleInfo

### PR DESCRIPTION
**Pull request by fumu-no-kagomeko**

### CODE REVIEW

**Comment by Princess-of-Sleeping** [comment]
There are still parts you can fix
```
typedef struct SceKernelModuleInfo {
	SceUInt size;                       //!< 0x1B8 for Vita 1.x
	SceUID modid;
	uint16_t modattr;
	uint8_t  modver[2];
	char module_name[28];
	SceUInt unk28;
	int (* module_start)(SceSize argc, void *args);
	int (* module_stop)(SceSize argc, void *args);
	int (* module_exit)(SceSize argc, void *args);
	void *exidxTop;
	void *exidxBtm;
	void *extabTop;
	void *extabBtm;
	void *tlsInit;
	SceSize tlsInitSize;
	SceSize tlsAreaSize;
	char path[256];
	SceKernelSegmentInfo segments[4];
	SceUInt type;                       //!< 6 = user-mode PRX?
} SceKernelModuleInfo;
```

**Comment by Princess-of-Sleeping** [comment]
you can fix?
```
typedef struct
{
  SceSize size;   //!< this structure size (0x18)
  SceUInt perms;  //!< probably rwx in low bits
  void *vaddr;    //!< address in memory
  SceSize memsz;  //!< size in memory
  SceSize filesz;  //!< original size of memsz
  SceUInt res;    //!< unused
} SceKernelSegmentInfo;
```

**Comment by d3m3vilurr** [comment]
if this patch is a right, I'll merge it now.
@Princess-of-Sleeping and you can make the next patch about SceKernelSegmentInfo & SceKernelModuleInfo. how do you think about it? :)

**Comment by Princess-of-Sleeping** [comment]
This fix is ​​correct.
After consulting with CelesteBlue, send a modified pull request for SceKernelSegmentInfo and SceKernelModuleInfo.

**Pull request merged**
