### PR TITLE
psp2: Add sceKernelUnlockLwMutex2

### PR DESCRIPTION
**Pull request by VelocityRa**

### CODE REVIEW

**Comment by frangarcj** [comment]
any objection?

**Comment by CelesteBlue-dev** [comment]
What does mean "fix regression" ?
Where did you find this function name ? Is there a definition ?

**Comment by Rinnegatamante** [comment]
"Fix regression" means it fixes a regression...

**Comment by d3m3vilurr** [comment]
we don't need to have conversation about vita3k's patch :>

**Comment by d3m3vilurr** [comment]
@VelocityRa is it part of `psp2kern`? imo it is part of `psp2`

**Comment by Rinnegatamante** [comment]
No one is talking about Vita3K patch. That's an automatic reference GitHub does when a commit/PR is mentioned in another commit/PR regardless of the repository.

**Comment by Rinnegatamante** [comment]
As mentioned on discord btw, this is not psp2kern but psp2 and the naming (of the new nid or the current one in db.yml) is probably sceKernelUnlockLwMutexCB.

**Comment by VelocityRa** [comment]
Discussed on Discord as to why it's unlikely to be a callback function, changed `psp2kern` -> `psp2`.

**Pull request merged**
