### PR TITLE
Fix 0x50FE3B4D from ksceSysrootIsManufacturingMode to ksceSysrootUseI…

### PR DESCRIPTION
**Pull request by CelesteBlue-dev**
…nternalStorage

Thanks to SKGleba

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
1.5yr ago, this nid was added from @TheOfficialFloW #139 then removed from @yifanlu cuz dup nid #172 
should review from one of them.

**Comment by yifanlu** [comment]
Please don’t remove headers. This isn’t how sdks work.

**Comment by CelesteBlue-dev** [comment]
@d3m3vilurr I have already explained to yifan why this is not IsManufacturingMode function and why it is UseExternalStorage.
The IsManufacturingMode function exists under this form only:
```c
int sceSblPmMgrGetCurrentMode(int *mode);
```
Returns 0 on success. mode is set to 1 if PSVita is in manufacturing mode.

**Comment by yifanlu** [comment]
Okay cool so we’re breaking homebrew code again?

**Comment by CelesteBlue-dev** [comment]
nothing uses this function for now as it was not useful to know if vita was in manufacturing mode.
Now that we know it indicates if memcard is allowed to be used, it will maybe be used in storage plugins...

**Comment by d3m3vilurr** [comment]
@yifanlu I said before about the version, but nobody start this :( anyway, maybe we need define macro for avoid sdk break

**Comment by d3m3vilurr** [comment]
@yifanlu pushed 0ebd19f0c8bdb then made issue #331

**Comment by yifanlu** [comment]
Thanks!

**Pull request merged**
